// Branding asset storage. The owner uploads logo + favicon from
// /settings/branding; we keep a single canonical filename per asset
// (logo.{ext}, favicon.{ext}) so the manifest URL stays stable. PWA
// icons (192 / 512 / maskable-512) are generated by sharp on every
// logo upload and stashed under icons/.
//
// Logos uploaded with large transparent margins (a common export from
// design tools) render as a tiny glyph floating in a mostly-empty box
// when the sidebar tile sizes the image to height-fits-aspect-ratio.
// We trim transparent borders for raster uploads so the visible glyph
// fills its container. Trim happens on save and is also applied lazily
// on read for previously-uploaded assets — keyed by source mtime so
// the cached trimmed copy auto-rebuilds whenever the logo changes.

import { mkdir, writeFile, readFile, stat } from "node:fs/promises";
import { join } from "node:path";

const STORAGE_ROOT = process.env.STORAGE_ROOT ?? "/data";
export const BRANDING_DIR = join(STORAGE_ROOT, "uploads", "branding");
export const ICONS_DIR = join(BRANDING_DIR, "icons");
export const TRIM_CACHE_DIR = join(BRANDING_DIR, "trim-cache");

export const LOGO_MAX_BYTES = 2 * 1024 * 1024; // 2 MB
export const FAVICON_MAX_BYTES = 256 * 1024; // 256 KB

export const LOGO_MIME = ["image/png", "image/svg+xml", "image/jpeg", "image/webp"];
export const FAVICON_MIME = ["image/png", "image/x-icon", "image/vnd.microsoft.icon", "image/svg+xml"];

export type SavedAsset = {
  /** Disk path inside the container. */
  path: string;
  /** Public URL (served from /api/branding/...). */
  url: string;
  /** File extension including dot, e.g. ".png". */
  ext: string;
};

function extFromMime(mime: string): string {
  switch (mime) {
    case "image/png":
      return ".png";
    case "image/svg+xml":
      return ".svg";
    case "image/jpeg":
      return ".jpg";
    case "image/webp":
      return ".webp";
    case "image/x-icon":
    case "image/vnd.microsoft.icon":
      return ".ico";
    default:
      return ".bin";
  }
}

async function ensureDir(): Promise<void> {
  await mkdir(BRANDING_DIR, { recursive: true });
  await mkdir(ICONS_DIR, { recursive: true });
  await mkdir(TRIM_CACHE_DIR, { recursive: true });
}

/**
 * Trim transparent / near-uniform borders from a raster logo. Returns
 * the original buffer unchanged when sharp isn't available, when the
 * source has no detectable border to crop, or on any error — trim is a
 * cosmetic improvement, never load-bearing.
 */
async function trimRaster(buffer: Buffer): Promise<Buffer> {
  try {
    const { default: sharp } = await import(/* webpackIgnore: true */ "sharp");
    // threshold=10 picks up faint anti-aliased edges; default is 10 anyway
    // but spelling it out keeps the intent legible.
    const trimmed = await sharp(buffer)
      .trim({ threshold: 10 })
      .toBuffer();
    return trimmed;
  } catch {
    return buffer;
  }
}

export async function saveLogo(buffer: Buffer, mime: string): Promise<SavedAsset> {
  if (!LOGO_MIME.includes(mime)) {
    throw new Error(`Logo: unsupported type ${mime}. Use PNG, SVG, JPEG or WebP.`);
  }
  if (buffer.byteLength > LOGO_MAX_BYTES) {
    throw new Error(`Logo: file too large (${buffer.byteLength} bytes; max ${LOGO_MAX_BYTES}).`);
  }
  await ensureDir();
  const ext = extFromMime(mime);
  const path = join(BRANDING_DIR, `logo${ext}`);
  // Trim transparent margins on raster uploads so the visible glyph
  // fills the sidebar tile instead of floating in a near-empty box.
  // SVGs are left alone — viewBox handles their framing.
  const finalBuffer = mime === "image/svg+xml" ? buffer : await trimRaster(buffer);
  await writeFile(path, finalBuffer);
  return { path, url: `/api/branding/logo?v=${Date.now()}`, ext };
}

export async function saveFavicon(buffer: Buffer, mime: string): Promise<SavedAsset> {
  if (!FAVICON_MIME.includes(mime)) {
    throw new Error(`Favicon: unsupported type ${mime}. Use PNG, ICO or SVG.`);
  }
  if (buffer.byteLength > FAVICON_MAX_BYTES) {
    throw new Error(`Favicon: file too large (${buffer.byteLength} bytes; max ${FAVICON_MAX_BYTES}).`);
  }
  await ensureDir();
  const ext = extFromMime(mime);
  const path = join(BRANDING_DIR, `favicon${ext}`);
  await writeFile(path, buffer);
  return { path, url: `/api/branding/favicon?v=${Date.now()}`, ext };
}

export async function findAssetPath(name: "logo" | "favicon"): Promise<{ path: string; ext: string } | null> {
  const candidates = name === "logo"
    ? [".png", ".svg", ".webp", ".jpg"]
    : [".ico", ".png", ".svg"];
  for (const ext of candidates) {
    const path = join(BRANDING_DIR, `${name}${ext}`);
    try {
      await stat(path);
      return { path, ext };
    } catch {
      // try next
    }
  }
  return null;
}

export async function readAsset(name: "logo" | "favicon"): Promise<{ bytes: Buffer; ext: string } | null> {
  const found = await findAssetPath(name);
  if (!found) return null;
  // For raster logos, prefer a trimmed copy so previously-uploaded
  // assets with large transparent margins also display correctly
  // without requiring a re-upload. Cache the trimmed bytes on disk
  // keyed by source mtime — invalidates automatically on overwrite.
  if (name === "logo" && found.ext !== ".svg") {
    try {
      const trimmed = await readOrBuildTrimmedLogo(found.path, found.ext);
      if (trimmed) return { bytes: trimmed, ext: found.ext };
    } catch {
      // fall through to raw bytes
    }
  }
  const bytes = await readFile(found.path);
  return { bytes, ext: found.ext };
}

/**
 * Returns the trimmed-margin version of the source logo, building +
 * caching it on disk if the cached copy is missing or stale relative
 * to the source mtime. Returns null if sharp isn't available or
 * trimming throws — callers fall back to the raw bytes.
 */
async function readOrBuildTrimmedLogo(
  sourcePath: string,
  ext: string,
): Promise<Buffer | null> {
  await mkdir(TRIM_CACHE_DIR, { recursive: true });
  const sourceStat = await stat(sourcePath);
  const cacheKey = Math.floor(sourceStat.mtimeMs).toString(36);
  const cachePath = join(TRIM_CACHE_DIR, `logo.${cacheKey}${ext}`);
  try {
    return await readFile(cachePath);
  } catch {
    // Build the cache entry.
  }
  let trimmed: Buffer;
  try {
    const { default: sharp } = await import(/* webpackIgnore: true */ "sharp");
    trimmed = await sharp(sourcePath).trim({ threshold: 10 }).toBuffer();
  } catch {
    return null;
  }
  try {
    await writeFile(cachePath, trimmed);
  } catch {
    // Caching is best-effort; still return the buffer we built.
  }
  return trimmed;
}

/**
 * mtime-based version string for an uploaded asset, suitable for stamping
 * onto `<link rel="icon">` query params so browsers fetch a fresh URL
 * after upload instead of relying on Cache-Control headers (which mobile
 * browsers in particular love to ignore for favicons).
 *
 * Returns "default" when no asset has been uploaded — that's a stable
 * value so the cache key for the fallback initials icon stays the same
 * across page loads.
 */
export async function assetVersion(
  name: "logo" | "favicon",
): Promise<string> {
  const found = await findAssetPath(name);
  if (!found) return "default";
  try {
    const s = await stat(found.path);
    return Math.floor(s.mtimeMs).toString(36);
  } catch {
    return "default";
  }
}

export async function findIconPath(
  size: "192" | "512" | "maskable-512",
): Promise<string | null> {
  const path = join(ICONS_DIR, `icon-${size}.png`);
  try {
    await stat(path);
    return path;
  } catch {
    return null;
  }
}

/**
 * Generate the three PWA icons from a source logo. Uses sharp at runtime
 * so the dependency only loads when the owner actually uploads. Maskable
 * icons get a 16% safe-zone padding (PWA spec recommendation).
 */
export async function generateIcons(sourceLogoPath: string): Promise<void> {
  await ensureDir();
  const { default: sharp } = await import(/* webpackIgnore: true */ "sharp");
  const source = sharp(sourceLogoPath);
  await source
    .clone()
    .resize(192, 192, { fit: "contain", background: { r: 255, g: 255, b: 255, alpha: 0 } })
    .png()
    .toFile(join(ICONS_DIR, "icon-192.png"));
  await source
    .clone()
    .resize(512, 512, { fit: "contain", background: { r: 255, g: 255, b: 255, alpha: 0 } })
    .png()
    .toFile(join(ICONS_DIR, "icon-512.png"));
  // Maskable: shrink to 80% of the canvas so the safe zone clears the OS mask.
  await source
    .clone()
    .resize(410, 410, { fit: "contain", background: { r: 255, g: 255, b: 255, alpha: 0 } })
    .extend({
      top: 51,
      bottom: 51,
      left: 51,
      right: 51,
      background: { r: 255, g: 255, b: 255, alpha: 1 },
    })
    .resize(512, 512)
    .png()
    .toFile(join(ICONS_DIR, "icon-maskable-512.png"));
}

/**
 * SVG fallback for the manifest icons when the owner hasn't uploaded a
 * logo yet. Renders the company initials on a brand-colored square.
 */
export function fallbackIconSvg(initials: string, brandColorHex: string, size: number): string {
  const fontSize = Math.round(size * 0.42);
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}">
  <rect width="${size}" height="${size}" rx="${Math.round(size * 0.18)}" fill="${brandColorHex}" />
  <text x="50%" y="52%" text-anchor="middle" dominant-baseline="middle"
        font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"
        font-weight="700" font-size="${fontSize}" fill="white">${initials}</text>
</svg>`;
}
