// Branding asset storage. The owner uploads logo + favicon from
// /settings/branding; we keep a single canonical filename per asset
// (logo.{ext}, favicon.{ext}) so the manifest URL stays stable. PWA
// icons (192 / 512 / maskable-512) are generated by sharp on every
// logo upload and stashed under icons/.

import { mkdir, writeFile, readFile, stat } from "node:fs/promises";
import { join } from "node:path";

const STORAGE_ROOT = process.env.STORAGE_ROOT ?? "/data";
export const BRANDING_DIR = join(STORAGE_ROOT, "uploads", "branding");
export const ICONS_DIR = join(BRANDING_DIR, "icons");

export const LOGO_MAX_BYTES = 2 * 1024 * 1024; // 2 MB
export const FAVICON_MAX_BYTES = 256 * 1024; // 256 KB

export const LOGO_MIME = ["image/png", "image/svg+xml", "image/jpeg", "image/webp"];
export const FAVICON_MIME = ["image/png", "image/x-icon", "image/vnd.microsoft.icon", "image/svg+xml"];

export type SavedAsset = {
  /** Disk path inside the container. */
  path: string;
  /** Public URL (served from /api/branding/...). */
  url: string;
  /** File extension including dot, e.g. ".png". */
  ext: string;
};

function extFromMime(mime: string): string {
  switch (mime) {
    case "image/png":
      return ".png";
    case "image/svg+xml":
      return ".svg";
    case "image/jpeg":
      return ".jpg";
    case "image/webp":
      return ".webp";
    case "image/x-icon":
    case "image/vnd.microsoft.icon":
      return ".ico";
    default:
      return ".bin";
  }
}

async function ensureDir(): Promise<void> {
  await mkdir(BRANDING_DIR, { recursive: true });
  await mkdir(ICONS_DIR, { recursive: true });
}

export async function saveLogo(buffer: Buffer, mime: string): Promise<SavedAsset> {
  if (!LOGO_MIME.includes(mime)) {
    throw new Error(`Logo: unsupported type ${mime}. Use PNG, SVG, JPEG or WebP.`);
  }
  if (buffer.byteLength > LOGO_MAX_BYTES) {
    throw new Error(`Logo: file too large (${buffer.byteLength} bytes; max ${LOGO_MAX_BYTES}).`);
  }
  await ensureDir();
  const ext = extFromMime(mime);
  const path = join(BRANDING_DIR, `logo${ext}`);
  await writeFile(path, buffer);
  return { path, url: `/api/branding/logo?v=${Date.now()}`, ext };
}

export async function saveFavicon(buffer: Buffer, mime: string): Promise<SavedAsset> {
  if (!FAVICON_MIME.includes(mime)) {
    throw new Error(`Favicon: unsupported type ${mime}. Use PNG, ICO or SVG.`);
  }
  if (buffer.byteLength > FAVICON_MAX_BYTES) {
    throw new Error(`Favicon: file too large (${buffer.byteLength} bytes; max ${FAVICON_MAX_BYTES}).`);
  }
  await ensureDir();
  const ext = extFromMime(mime);
  const path = join(BRANDING_DIR, `favicon${ext}`);
  await writeFile(path, buffer);
  return { path, url: `/api/branding/favicon?v=${Date.now()}`, ext };
}

export async function findAssetPath(name: "logo" | "favicon"): Promise<{ path: string; ext: string } | null> {
  const candidates = name === "logo"
    ? [".png", ".svg", ".webp", ".jpg"]
    : [".ico", ".png", ".svg"];
  for (const ext of candidates) {
    const path = join(BRANDING_DIR, `${name}${ext}`);
    try {
      await stat(path);
      return { path, ext };
    } catch {
      // try next
    }
  }
  return null;
}

export async function readAsset(name: "logo" | "favicon"): Promise<{ bytes: Buffer; ext: string } | null> {
  const found = await findAssetPath(name);
  if (!found) return null;
  const bytes = await readFile(found.path);
  return { bytes, ext: found.ext };
}

export async function findIconPath(
  size: "192" | "512" | "maskable-512",
): Promise<string | null> {
  const path = join(ICONS_DIR, `icon-${size}.png`);
  try {
    await stat(path);
    return path;
  } catch {
    return null;
  }
}

/**
 * Generate the three PWA icons from a source logo. Uses sharp at runtime
 * so the dependency only loads when the owner actually uploads. Maskable
 * icons get a 16% safe-zone padding (PWA spec recommendation).
 */
export async function generateIcons(sourceLogoPath: string): Promise<void> {
  await ensureDir();
  const { default: sharp } = await import(/* webpackIgnore: true */ "sharp");
  const source = sharp(sourceLogoPath);
  await source
    .clone()
    .resize(192, 192, { fit: "contain", background: { r: 255, g: 255, b: 255, alpha: 0 } })
    .png()
    .toFile(join(ICONS_DIR, "icon-192.png"));
  await source
    .clone()
    .resize(512, 512, { fit: "contain", background: { r: 255, g: 255, b: 255, alpha: 0 } })
    .png()
    .toFile(join(ICONS_DIR, "icon-512.png"));
  // Maskable: shrink to 80% of the canvas so the safe zone clears the OS mask.
  await source
    .clone()
    .resize(410, 410, { fit: "contain", background: { r: 255, g: 255, b: 255, alpha: 0 } })
    .extend({
      top: 51,
      bottom: 51,
      left: 51,
      right: 51,
      background: { r: 255, g: 255, b: 255, alpha: 1 },
    })
    .resize(512, 512)
    .png()
    .toFile(join(ICONS_DIR, "icon-maskable-512.png"));
}

/**
 * SVG fallback for the manifest icons when the owner hasn't uploaded a
 * logo yet. Renders the company initials on a brand-colored square.
 */
export function fallbackIconSvg(initials: string, brandColorHex: string, size: number): string {
  const fontSize = Math.round(size * 0.42);
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}">
  <rect width="${size}" height="${size}" rx="${Math.round(size * 0.18)}" fill="${brandColorHex}" />
  <text x="50%" y="52%" text-anchor="middle" dominant-baseline="middle"
        font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"
        font-weight="700" font-size="${fontSize}" fill="white">${initials}</text>
</svg>`;
}
