#!/usr/bin/env bash
# One-shot installer for LX120 (or any LXC / VM that should pull-and-run the
# rebuilt payroll app from GitHub).
#
# What this does:
#   1. Installs Docker (engine + compose) if missing.
#   2. Clones (or fetches) kidevu123/payroll into /opt/payroll.
#   3. Drops in /etc/payroll/.env (interactive — prompts for secrets).
#   4. Installs the payroll-deploy.{service,timer} systemd units that pull
#      and re-up the stack every 60 seconds against the configured branch.
#   5. Starts everything.
#
# Re-running is safe; each step is idempotent.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/kidevu123/payroll/rebuild/foundation/deploy/lxc/install.sh | bash -s -- rebuild/foundation
#
# Or, if you've already cloned:
#   bash deploy/lxc/install.sh [branch]
#
# Default branch is rebuild/foundation. Switch to main once Phase 1 ships.

set -euo pipefail

BRANCH="${1:-rebuild/foundation}"
REPO_URL="${REPO_URL:-https://github.com/kidevu123/payroll.git}"
APP_DIR="${APP_DIR:-/opt/payroll}"
ENV_DIR="/etc/payroll"
ENV_FILE="${ENV_DIR}/.env"
SYSTEMD_DIR="/etc/systemd/system"

require_root() {
  if [[ $EUID -ne 0 ]]; then
    echo "Run as root (sudo)." >&2
    exit 1
  fi
}

install_docker() {
  if command -v docker >/dev/null 2>&1; then
    echo "[docker] already installed: $(docker --version)"
    return
  fi
  echo "[docker] installing engine + compose plugin..."
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  . /etc/os-release
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/${ID} ${VERSION_CODENAME} stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
}

clone_repo() {
  if [[ -d "${APP_DIR}/.git" ]]; then
    echo "[repo] already cloned at ${APP_DIR}; fetching..."
    git -C "${APP_DIR}" fetch --quiet origin
  else
    echo "[repo] cloning ${REPO_URL} into ${APP_DIR}..."
    mkdir -p "$(dirname "${APP_DIR}")"
    git clone --quiet "${REPO_URL}" "${APP_DIR}"
  fi
  git -C "${APP_DIR}" checkout --quiet "${BRANCH}"
  git -C "${APP_DIR}" reset --hard --quiet "origin/${BRANCH}"
}

vapid_keypair() {
  # Generate a VAPID keypair using openssl. Outputs two lines:
  #   <base64url-private 32 bytes>
  #   <base64url-public 65 bytes (uncompressed: 0x04 || X || Y)>
  # web-push consumes both as URL-safe base64 with padding stripped.
  local tmp priv pub
  tmp="$(mktemp)"
  openssl ecparam -name prime256v1 -genkey -noout -out "${tmp}" >/dev/null 2>&1
  priv="$(openssl ec -in "${tmp}" -outform DER 2>/dev/null \
    | tail -c +8 | head -c 32 \
    | base64 | tr '/+' '_-' | tr -d '=')"
  pub="$(openssl ec -in "${tmp}" -pubout -outform DER 2>/dev/null \
    | tail -c 65 \
    | base64 | tr '/+' '_-' | tr -d '=')"
  rm -f "${tmp}"
  printf '%s\n%s\n' "${priv}" "${pub}"
}

ensure_env() {
  mkdir -p "${ENV_DIR}"
  if [[ -f "${ENV_FILE}" ]]; then
    echo "[env] ${ENV_FILE} exists; checking for missing secrets"
    # Append-only: backfill VAPID keys if they aren't there yet, but never
    # rotate values the operator already has — rotating breaks every existing
    # PushSubscription row.
    if ! grep -q '^VAPID_PUBLIC_KEY=' "${ENV_FILE}"; then
      echo "[env] backfilling VAPID keys"
      mapfile -t VAPID < <(vapid_keypair)
      {
        echo
        echo "# Web Push (VAPID) — generated $(date -Is)"
        echo "VAPID_PRIVATE_KEY=${VAPID[0]}"
        echo "VAPID_PUBLIC_KEY=${VAPID[1]}"
        echo "VAPID_CONTACT_EMAIL=admin@example.com"
      } >> "${ENV_FILE}"
      chmod 600 "${ENV_FILE}"
    fi
    return
  fi
  echo "[env] generating ${ENV_FILE} with random secrets"
  AUTH_SECRET="$(openssl rand -base64 48)"
  VAULT_KEY="$(openssl rand -base64 32)"
  POSTGRES_PASSWORD="$(openssl rand -hex 24)"
  mapfile -t VAPID < <(vapid_keypair)
  cat > "${ENV_FILE}" <<EOF
# Generated by deploy/lxc/install.sh on $(date -Is)
# Edit these AFTER first run; AUTH_SECRET rotation invalidates sessions.

AUTH_SECRET=${AUTH_SECRET}
NGTECO_VAULT_KEY=${VAULT_KEY}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Web Push (VAPID). Rotating these breaks every existing PushSubscription
# row — the install script never overwrites them on a re-run.
VAPID_PRIVATE_KEY=${VAPID[0]}
VAPID_PUBLIC_KEY=${VAPID[1]}
VAPID_CONTACT_EMAIL=admin@example.com

# Public URL the app serves at; update once HTTPS is fronting it.
APP_URL=http://$(hostname -I | awk '{print $1}'):3000
TRUST_PROXY=false

# Optional: point at the Grafana stack if you have one running.
OTEL_EXPORTER_OTLP_ENDPOINT=
OTEL_SERVICE_NAME=payroll

# Backup retention (days)
BACKUP_RETENTION_DAYS=30
EOF
  chmod 600 "${ENV_FILE}"
  echo "[env] wrote ${ENV_FILE} (mode 0600)"
}

link_env() {
  # docker compose looks for .env in the project root.
  ln -sf "${ENV_FILE}" "${APP_DIR}/.env"
}

install_systemd() {
  install -m 0644 "${APP_DIR}/deploy/lxc/payroll-deploy.service" "${SYSTEMD_DIR}/payroll-deploy.service"
  install -m 0644 "${APP_DIR}/deploy/lxc/payroll-deploy.timer" "${SYSTEMD_DIR}/payroll-deploy.timer"
  # Drop a small env override so the service knows which branch to track.
  mkdir -p "${SYSTEMD_DIR}/payroll-deploy.service.d"
  cat > "${SYSTEMD_DIR}/payroll-deploy.service.d/override.conf" <<EOF
[Service]
Environment=PAYROLL_BRANCH=${BRANCH}
Environment=PAYROLL_DIR=${APP_DIR}
EOF
  systemctl daemon-reload
  systemctl enable --now payroll-deploy.timer
  echo "[systemd] payroll-deploy.timer enabled (every 60s)"
}

main() {
  require_root
  install_docker
  clone_repo
  ensure_env
  link_env
  install_systemd
  # First run: build and start now without waiting for the timer.
  systemctl start payroll-deploy.service
  echo
  echo "Done. App will come up shortly at http://$(hostname -I | awk '{print $1}'):3000"
  echo "Watch logs with:  journalctl -u payroll-deploy -f"
  echo "Watch the app:    docker compose -f ${APP_DIR}/docker-compose.yml logs -f app"
}

main "$@"
