// Kiosk copy, typed and local. The kiosk is a standalone surface with a
// dozen strings — a local dictionary keyed by the employee's language
// keeps pages fast (no i18n provider) and the two variants side by side.

export type KioskLang = "en" | "es";

const en = {
  hi: "Hi",
  autoSignOut: "Signs out in",
  exit: "Exit",
  myHours: "My hours",
  myHoursSub: "This week so far",
  myPay: "My pay",
  myPaySub: "Recent payslips",
  fixPunch: "Fix a punch",
  fixPunchSub: "Forgot to clock in or out?",
  sentBanner: "Sent. The office will review it.",
  period: "Week",
  total: "Total",
  in: "In",
  out: "Out",
  hours: "Hours",
  open: "still in",
  noPunches: "No punches",
  missingOut: "Missing clock-out",
  unpaired: "Needs a fix",
  ok: "OK",
  net: "Pay",
  noPayslips: "No payslips yet.",
  pickDay: "Which day needs a fix?",
  today: "Today",
  back: "Back",
  whatHappened: "What happened?",
  send: "Send to office",
  sending: "Sending...",
  reasonForgot: "I forgot to punch",
  reasonClock: "The time clock did not take my punch",
  reasonLeftEarly: "I left early / came in late",
  forgotIn: "I forgot to clock in",
  forgotOut: "I forgot to clock out",
  whenIn: "When did you clock in?",
  whenOut: "When did you clock out?",
  onFile: "Already on file",
  unpairedHint: "We have one punch for this day. Tell us which one is missing.",
  clockIn: "Clock in",
  clockOut: "Clock out",
  inReview: "Pending review",
  payApproveTitle: "New payslip — needs your OK",
  payApprove: "Approve",
  payApprovedBanner: "Payslip approved. Thank you.",
  timeOffTile: "Time off",
  timeOffTileSub: "Request a day off",
  timeOffType: "What kind?",
  typeSick: "Sick",
  typePersonal: "Personal",
  typeUnpaid: "Unpaid day",
  typeOther: "Other",
  firstDay: "First day",
  lastDay: "Last day",
  timeOffOverlap: "You already asked for time off on these days.",
  datesBackwards: "The last day cannot be before the first day.",
};

const es: Record<keyof typeof en, string> = {
  hi: "Hola",
  autoSignOut: "Cierra sesion en",
  exit: "Salir",
  myHours: "Mis horas",
  myHoursSub: "Esta semana",
  myPay: "Mi pago",
  myPaySub: "Recibos recientes",
  fixPunch: "Corregir marcacion",
  fixPunchSub: "Olvido marcar entrada o salida?",
  sentBanner: "Enviado. La oficina lo revisara.",
  period: "Semana",
  total: "Total",
  in: "Entrada",
  out: "Salida",
  hours: "Horas",
  open: "sin salida",
  noPunches: "Sin marcaciones",
  missingOut: "Falta la salida",
  unpaired: "Necesita correccion",
  ok: "OK",
  net: "Pago",
  noPayslips: "Aun no hay recibos.",
  pickDay: "Que dia necesita correccion?",
  today: "Hoy",
  back: "Atras",
  whatHappened: "Que paso?",
  send: "Enviar a la oficina",
  sending: "Enviando...",
  reasonForgot: "Olvide marcar",
  reasonClock: "El reloj no registro mi marcacion",
  reasonLeftEarly: "Sali temprano / llegue tarde",
  forgotIn: "Olvide marcar la entrada",
  forgotOut: "Olvide marcar la salida",
  whenIn: "A que hora entro?",
  whenOut: "A que hora salio?",
  onFile: "Ya registrado",
  unpairedHint: "Hay una marcacion este dia. Diganos cual falta.",
  clockIn: "Entrada",
  clockOut: "Salida",
  inReview: "En revision",
  payApproveTitle: "Recibo nuevo — necesita su OK",
  payApprove: "Aprobar",
  payApprovedBanner: "Recibo aprobado. Gracias.",
  timeOffTile: "Dias libres",
  timeOffTileSub: "Pedir un dia libre",
  timeOffType: "Que tipo?",
  typeSick: "Enfermo",
  typePersonal: "Personal",
  typeUnpaid: "Dia sin pago",
  typeOther: "Otro",
  firstDay: "Primer dia",
  lastDay: "Ultimo dia",
  timeOffOverlap: "Ya pidio dias libres en esas fechas.",
  datesBackwards: "El ultimo dia no puede ser antes del primero.",
};

export type KioskCopy = typeof en;

export function kioskCopy(lang: KioskLang): KioskCopy {
  return lang === "es" ? es : en;
}
