// Web Push dispatcher. Sends a push to every PushSubscription row for
// the given user. Failed endpoints (410 Gone) are pruned automatically.
//
// VAPID keys come from /etc/payroll/.env (generated by install.sh):
//   VAPID_PUBLIC_KEY (base64url, 65 bytes)
//   VAPID_PRIVATE_KEY (base64url, 32 bytes)
//   VAPID_CONTACT_EMAIL (mailto: target for the subscriber server)
//
// web-push is dynamically imported inside the dispatch function so the
// node-only code never reaches the edge bundle.

import { eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { pushSubscriptions } from "@/lib/db/schema";
import { logger } from "@/lib/telemetry";

export type PushPayload = {
  title: string;
  body: string;
  url: string;
  tag?: string;
};

export function vapidPublicKey(): string | null {
  return process.env.VAPID_PUBLIC_KEY ?? null;
}

/**
 * Returns true when both VAPID keys + a contact email are present, so the
 * UI can decide whether the "Enable notifications" prompt would actually
 * work. We don't validate key length here — that's web-push's job.
 */
export function vapidConfigured(): boolean {
  return Boolean(
    process.env.VAPID_PUBLIC_KEY &&
      process.env.VAPID_PRIVATE_KEY &&
      process.env.VAPID_CONTACT_EMAIL,
  );
}

export async function dispatchPush(
  recipientId: string,
  payload: PushPayload,
): Promise<{ sent: number; pruned: number }> {
  const subs = await db
    .select()
    .from(pushSubscriptions)
    .where(eq(pushSubscriptions.userId, recipientId));
  if (subs.length === 0) return { sent: 0, pruned: 0 };

  const publicKey = process.env.VAPID_PUBLIC_KEY;
  const privateKey = process.env.VAPID_PRIVATE_KEY;
  const contact = process.env.VAPID_CONTACT_EMAIL ?? "noreply@example.com";
  if (!publicKey || !privateKey) {
    logger.warn(
      { recipientId, kind: payload.tag ?? "unknown" },
      "dispatchPush: VAPID keys not configured; skipping",
    );
    return { sent: 0, pruned: 0 };
  }

  // webpackIgnore: web-push is Node-only and pulls fs/url that we don't want
  // in the edge bundle of instrumentation.ts.
  const wp = (await import(
    /* webpackIgnore: true */ "web-push"
  )) as typeof import("web-push");
  wp.setVapidDetails(`mailto:${contact}`, publicKey, privateKey);

  let sent = 0;
  let pruned = 0;
  const dead: string[] = [];
  await Promise.all(
    subs.map(async (s) => {
      try {
        await wp.sendNotification(
          {
            endpoint: s.endpoint,
            keys: { p256dh: s.p256dh, auth: s.auth },
          },
          JSON.stringify(payload),
        );
        sent++;
      } catch (err) {
        const status = (err as { statusCode?: number }).statusCode;
        if (status === 404 || status === 410) dead.push(s.id);
        else logger.warn({ err, endpoint: s.endpoint }, "push send failed");
      }
    }),
  );
  if (dead.length > 0) {
    for (const id of dead) {
      await db.delete(pushSubscriptions).where(eq(pushSubscriptions.id, id));
    }
    pruned = dead.length;
  }
  return { sent, pruned };
}
