// Payslip queries. Generated by the publish job; viewed by employee + admin.

import { and, eq } from "drizzle-orm";
import { db } from "@/lib/db";
import {
  payslips,
  type Payslip,
  type NewPayslip,
} from "@/lib/db/schema";
import { writeAudit } from "@/lib/db/audit";

export type Actor = {
  id: string;
  role: "OWNER" | "ADMIN" | "EMPLOYEE";
};

export async function listPayslipsForPeriod(periodId: string): Promise<Payslip[]> {
  return db.select().from(payslips).where(eq(payslips.periodId, periodId));
}

export async function listPayslipsForEmployee(employeeId: string): Promise<Payslip[]> {
  return db.select().from(payslips).where(eq(payslips.employeeId, employeeId));
}

export async function getPayslip(id: string): Promise<Payslip | null> {
  const [row] = await db.select().from(payslips).where(eq(payslips.id, id));
  return row ?? null;
}

export async function getPayslipForEmployeePeriod(
  employeeId: string,
  periodId: string,
): Promise<Payslip | null> {
  const [row] = await db
    .select()
    .from(payslips)
    .where(and(eq(payslips.employeeId, employeeId), eq(payslips.periodId, periodId)));
  return row ?? null;
}

export async function upsertPayslip(input: NewPayslip): Promise<Payslip> {
  const [row] = await db
    .insert(payslips)
    .values(input)
    .onConflictDoUpdate({
      target: [payslips.employeeId, payslips.periodId],
      set: {
        payrollRunId: input.payrollRunId,
        hoursWorked: input.hoursWorked,
        grossPayCents: input.grossPayCents,
        roundedPayCents: input.roundedPayCents,
        taskPayCents: input.taskPayCents ?? 0,
        pdfPath: input.pdfPath ?? null,
        generatedAt: new Date(),
      },
    })
    .returning();
  if (!row) throw new Error("upsertPayslip: no row returned");
  return row;
}

export async function markAcknowledged(id: string, actor: Actor): Promise<Payslip> {
  return db.transaction(async (tx) => {
    const [before] = await tx.select().from(payslips).where(eq(payslips.id, id));
    if (!before) throw new Error(`markAcknowledged: ${id} not found`);
    if (before.acknowledgedAt) return before;
    const [row] = await tx
      .update(payslips)
      .set({ acknowledgedAt: new Date() })
      .where(eq(payslips.id, id))
      .returning();
    if (!row) throw new Error("markAcknowledged: returning() empty");
    await writeAudit(
      {
        actorId: actor.id,
        actorRole: actor.role,
        action: "payslip.acknowledge",
        targetType: "Payslip",
        targetId: id,
        before,
        after: row,
      },
      tx,
    );
    return row;
  });
}

export async function markPublished(payrollRunId: string): Promise<void> {
  await db
    .update(payslips)
    .set({ publishedAt: new Date() })
    .where(eq(payslips.payrollRunId, payrollRunId));
}
