// Payslip queries. Generated by the publish job; viewed by employee + admin.
//
// Employee-facing reads enforce the publish gate:
//   • payroll_runs.published_to_portal_at must be non-null for the run that
//     owns the payslip. Until the admin clicks Publish, the payslip stays
//     internal-only.

import { and, eq, isNotNull } from "drizzle-orm";
import { db } from "@/lib/db";
import {
  payrollRuns,
  payslips,
  type Payslip,
  type NewPayslip,
} from "@/lib/db/schema";
import { writeAudit } from "@/lib/db/audit";

export type Actor = {
  id: string;
  role: "OWNER" | "ADMIN" | "EMPLOYEE";
};

export async function listPayslipsForPeriod(periodId: string): Promise<Payslip[]> {
  return db.select().from(payslips).where(eq(payslips.periodId, periodId));
}

export async function listPayslipsForEmployee(employeeId: string): Promise<Payslip[]> {
  return db.select().from(payslips).where(eq(payslips.employeeId, employeeId));
}

/**
 * Same as listPayslipsForEmployee, but filtered to runs the admin has
 * published to the employee portal. This is the read used by /me/pay.
 */
export async function listPublishedPayslipsForEmployee(
  employeeId: string,
): Promise<Payslip[]> {
  const rows = await db
    .select({ p: payslips })
    .from(payslips)
    .innerJoin(payrollRuns, eq(payslips.payrollRunId, payrollRuns.id))
    .where(
      and(
        eq(payslips.employeeId, employeeId),
        isNotNull(payrollRuns.publishedToPortalAt),
      ),
    );
  return rows.map((r) => r.p);
}

/**
 * Returns true iff the payslip belongs to a run that's been published to
 * the portal. Used by /api/payslips/[id]/pdf to gate non-admin access.
 */
export async function isPayslipPublishedToPortal(payslipId: string): Promise<boolean> {
  const [row] = await db
    .select({ portalAt: payrollRuns.publishedToPortalAt })
    .from(payslips)
    .innerJoin(payrollRuns, eq(payslips.payrollRunId, payrollRuns.id))
    .where(eq(payslips.id, payslipId));
  return !!row?.portalAt;
}

export async function getPayslip(id: string): Promise<Payslip | null> {
  const [row] = await db.select().from(payslips).where(eq(payslips.id, id));
  return row ?? null;
}

export async function getPayslipForEmployeePeriod(
  employeeId: string,
  periodId: string,
): Promise<Payslip | null> {
  const [row] = await db
    .select()
    .from(payslips)
    .where(and(eq(payslips.employeeId, employeeId), eq(payslips.periodId, periodId)));
  return row ?? null;
}

/**
 * Same as getPayslipForEmployeePeriod, but only returns the row when the
 * underlying payroll_run has been published to the portal. /me/pay/[id] uses
 * this so unpublished runs render the "no payslip yet" empty state instead
 * of leaking pre-publish drafts.
 */
export async function getPublishedPayslipForEmployeePeriod(
  employeeId: string,
  periodId: string,
): Promise<Payslip | null> {
  const rows = await db
    .select({ p: payslips })
    .from(payslips)
    .innerJoin(payrollRuns, eq(payslips.payrollRunId, payrollRuns.id))
    .where(
      and(
        eq(payslips.employeeId, employeeId),
        eq(payslips.periodId, periodId),
        isNotNull(payrollRuns.publishedToPortalAt),
      ),
    );
  return rows[0]?.p ?? null;
}

export async function upsertPayslip(input: NewPayslip): Promise<Payslip> {
  const [row] = await db
    .insert(payslips)
    .values(input)
    .onConflictDoUpdate({
      target: [payslips.employeeId, payslips.periodId],
      set: {
        payrollRunId: input.payrollRunId,
        hoursWorked: input.hoursWorked,
        grossPayCents: input.grossPayCents,
        roundedPayCents: input.roundedPayCents,
        taskPayCents: input.taskPayCents ?? 0,
        pdfPath: input.pdfPath ?? null,
        generatedAt: new Date(),
      },
    })
    .returning();
  if (!row) throw new Error("upsertPayslip: no row returned");
  return row;
}

export async function markAcknowledged(id: string, actor: Actor): Promise<Payslip> {
  return db.transaction(async (tx) => {
    const [before] = await tx.select().from(payslips).where(eq(payslips.id, id));
    if (!before) throw new Error(`markAcknowledged: ${id} not found`);
    if (before.acknowledgedAt) return before;
    const [row] = await tx
      .update(payslips)
      .set({ acknowledgedAt: new Date() })
      .where(eq(payslips.id, id))
      .returning();
    if (!row) throw new Error("markAcknowledged: returning() empty");
    await writeAudit(
      {
        actorId: actor.id,
        actorRole: actor.role,
        action: "payslip.acknowledge",
        targetType: "Payslip",
        targetId: id,
        before,
        after: row,
      },
      tx,
    );
    return row;
  });
}

export async function markPublished(payrollRunId: string): Promise<void> {
  await db
    .update(payslips)
    .set({ publishedAt: new Date() })
    .where(eq(payslips.payrollRunId, payrollRunId));
}
