// Payslip queries. Generated by the publish job; viewed by employee + admin.
//
// Employee-facing reads enforce the publish gate:
//   • payroll_runs.published_to_portal_at must be non-null for the run that
//     owns the payslip. Until the admin clicks Publish, the payslip stays
//     internal-only.

import { and, eq, isNotNull, isNull, sql } from "drizzle-orm";
import { db } from "@/lib/db";
import {
  payrollRuns,
  payslips,
  type Payslip,
  type NewPayslip,
} from "@/lib/db/schema";
import { writeAudit } from "@/lib/db/audit";

export type Actor = {
  id: string;
  role: "OWNER" | "ADMIN" | "EMPLOYEE";
};

export async function listPayslipsForPeriod(
  periodId: string,
  opts: { includeVoided?: boolean } = {},
): Promise<Payslip[]> {
  const conds = [eq(payslips.periodId, periodId)];
  if (!opts.includeVoided) conds.push(isNull(payslips.voidedAt));
  return db.select().from(payslips).where(and(...conds));
}

export async function listPayslipsForEmployee(
  employeeId: string,
  opts: { includeVoided?: boolean } = {},
): Promise<Payslip[]> {
  const conds = [eq(payslips.employeeId, employeeId)];
  if (!opts.includeVoided) conds.push(isNull(payslips.voidedAt));
  return db.select().from(payslips).where(and(...conds));
}

/**
 * Same as listPayslipsForEmployee, but filtered to runs the admin has
 * published to the employee portal. This is the read used by /me/pay.
 */
export async function listPublishedPayslipsForEmployee(
  employeeId: string,
): Promise<Payslip[]> {
  const rows = await db
    .select({ p: payslips })
    .from(payslips)
    .innerJoin(payrollRuns, eq(payslips.payrollRunId, payrollRuns.id))
    .where(
      and(
        eq(payslips.employeeId, employeeId),
        isNotNull(payrollRuns.publishedToPortalAt),
        isNull(payslips.voidedAt),
      ),
    );
  return rows.map((r) => r.p);
}

/**
 * Returns true iff the payslip belongs to a run that's been published to
 * the portal. Used by /api/payslips/[id]/pdf to gate non-admin access.
 */
export async function isPayslipPublishedToPortal(payslipId: string): Promise<boolean> {
  const [row] = await db
    .select({ portalAt: payrollRuns.publishedToPortalAt })
    .from(payslips)
    .innerJoin(payrollRuns, eq(payslips.payrollRunId, payrollRuns.id))
    .where(eq(payslips.id, payslipId));
  return !!row?.portalAt;
}

export async function getPayslip(id: string): Promise<Payslip | null> {
  const [row] = await db.select().from(payslips).where(eq(payslips.id, id));
  return row ?? null;
}

export async function getPayslipForEmployeePeriod(
  employeeId: string,
  periodId: string,
): Promise<Payslip | null> {
  const [row] = await db
    .select()
    .from(payslips)
    .where(and(eq(payslips.employeeId, employeeId), eq(payslips.periodId, periodId)));
  return row ?? null;
}

/**
 * Same as getPayslipForEmployeePeriod, but only returns the row when the
 * underlying payroll_run has been published to the portal. /me/pay/[id] uses
 * this so unpublished runs render the "no payslip yet" empty state instead
 * of leaking pre-publish drafts.
 */
export async function getPublishedPayslipForEmployeePeriod(
  employeeId: string,
  periodId: string,
): Promise<Payslip | null> {
  const rows = await db
    .select({ p: payslips })
    .from(payslips)
    .innerJoin(payrollRuns, eq(payslips.payrollRunId, payrollRuns.id))
    .where(
      and(
        eq(payslips.employeeId, employeeId),
        eq(payslips.periodId, periodId),
        isNotNull(payrollRuns.publishedToPortalAt),
        isNull(payslips.voidedAt),
      ),
    );
  return rows[0]?.p ?? null;
}

export async function upsertPayslip(input: NewPayslip): Promise<Payslip> {
  const [row] = await db
    .insert(payslips)
    .values(input)
    .onConflictDoUpdate({
      target: [payslips.employeeId, payslips.periodId],
      set: {
        payrollRunId: input.payrollRunId,
        hoursWorked: input.hoursWorked,
        grossPayCents: input.grossPayCents,
        roundedPayCents: input.roundedPayCents,
        taskPayCents: input.taskPayCents ?? 0,
        pdfPath: input.pdfPath ?? null,
        generatedAt: new Date(),
      },
    })
    .returning();
  if (!row) throw new Error("upsertPayslip: no row returned");
  return row;
}

export async function markAcknowledged(id: string, actor: Actor): Promise<Payslip> {
  return db.transaction(async (tx) => {
    const [before] = await tx.select().from(payslips).where(eq(payslips.id, id));
    if (!before) throw new Error(`markAcknowledged: ${id} not found`);
    if (before.acknowledgedAt) return before;
    const [row] = await tx
      .update(payslips)
      .set({ acknowledgedAt: new Date() })
      .where(eq(payslips.id, id))
      .returning();
    if (!row) throw new Error("markAcknowledged: returning() empty");
    await writeAudit(
      {
        actorId: actor.id,
        actorRole: actor.role,
        action: "payslip.acknowledge",
        targetType: "Payslip",
        targetId: id,
        before,
        after: row,
      },
      tx,
    );
    return row;
  });
}

export async function markPublished(payrollRunId: string): Promise<void> {
  await db
    .update(payslips)
    .set({ publishedAt: new Date() })
    .where(eq(payslips.payrollRunId, payrollRunId));
}

/**
 * Soft-delete a payslip from a run. Use case: an employee was incorrectly
 * included in a run (wrong cohort, wrong schedule) and the admin needs to
 * remove them after the fact — even on a PUBLISHED run. Voided payslips
 * are excluded from listings, totals, and the employee portal.
 *
 * Recomputes the parent run's total_amount_cents from non-voided payslips
 * so /reports rolls up correctly without re-publishing.
 */
export async function voidPayslip(
  id: string,
  reason: string,
  actor: Actor,
): Promise<Payslip> {
  if (!reason.trim()) throw new Error("voidPayslip: reason is required");
  return db.transaction(async (tx) => {
    const [before] = await tx.select().from(payslips).where(eq(payslips.id, id));
    if (!before) throw new Error(`voidPayslip: ${id} not found`);
    if (before.voidedAt) return before;
    const [row] = await tx
      .update(payslips)
      .set({
        voidedAt: new Date(),
        voidedById: actor.id,
        voidReason: reason,
      })
      .where(eq(payslips.id, id))
      .returning();
    if (!row) throw new Error("voidPayslip: returning() empty");
    await recomputeRunTotal(tx, before.payrollRunId);
    await writeAudit(
      {
        actorId: actor.id,
        actorRole: actor.role,
        action: "payslip.void",
        targetType: "Payslip",
        targetId: id,
        before,
        after: row,
      },
      tx,
    );
    return row;
  });
}

/** Reverse voidPayslip — for "I removed the wrong person, put them back". */
/**
 * Re-stamp a payslip's hoursWorked / grossPayCents / roundedPayCents from
 * the current set of (deduped, non-voided) punches in its period. Used
 * when historical data was imported with a stale total or after admin
 * voids/moves punches that should have changed the totals. Calls the
 * pure computePay so rounding rules match the publish handler.
 */
export async function recomputePayslip(
  id: string,
  actor: Actor,
): Promise<Payslip> {
  return db.transaction(async (tx) => {
    const [before] = await tx.select().from(payslips).where(eq(payslips.id, id));
    if (!before) throw new Error(`recomputePayslip: ${id} not found`);
    if (before.voidedAt) throw new Error("recomputePayslip: payslip is voided");

    // Lazy-load to avoid pulling computePay's transitive deps into edge bundles.
    const { listPunches } = await import("@/lib/db/queries/punches");
    const { listRates } = await import("@/lib/db/queries/rate-history");
    const { computePay } = await import("@/lib/payroll/computePay");
    const { dedupNearDuplicatePunches } = await import("@/lib/punches/dedup");
    const { getEmployee } = await import("@/lib/db/queries/employees");
    const { getSetting } = await import("@/lib/settings/runtime");

    const [employee, payRules, company, allPunches, rates] = await Promise.all([
      getEmployee(before.employeeId),
      getSetting("payRules"),
      getSetting("company"),
      listPunches({ employeeId: before.employeeId, periodId: before.periodId }),
      listRates(before.employeeId),
    ]);
    if (!employee) throw new Error("recomputePayslip: employee not found");
    const punches = dedupNearDuplicatePunches(allPunches);

    const result = computePay({
      punches,
      rateAt: (p) => {
        // Compare in company tz, not UTC, so a late-night ET punch doesn't
        // pick up a next-day rate change retroactively.
        const d = p.clockIn instanceof Date ? p.clockIn : new Date(p.clockIn);
        const day = new Intl.DateTimeFormat("en-CA", {
          timeZone: company.timezone,
        }).format(d);
        for (const r of rates) {
          if (r.effectiveFrom <= day) return r.hourlyRateCents;
        }
        return employee.hourlyRateCents ?? 0;
      },
      taskPay: [],
      timezone: company.timezone,
      rules: {
        rounding: payRules.rounding,
        hoursDecimalPlaces: payRules.hoursDecimalPlaces,
        ...(payRules.overtime.enabled
          ? {
              overtime: {
                thresholdHours: payRules.overtime.thresholdHours,
                multiplier: payRules.overtime.multiplier,
              },
            }
          : {}),
      },
    });

    const [row] = await tx
      .update(payslips)
      .set({
        hoursWorked: String(result.totalHours),
        grossPayCents: result.grossCents,
        roundedPayCents: result.roundedCents,
        taskPayCents: result.taskCents,
        generatedAt: new Date(),
      })
      .where(eq(payslips.id, id))
      .returning();
    if (!row) throw new Error("recomputePayslip: returning() empty");
    await recomputeRunTotal(tx, before.payrollRunId);
    await writeAudit(
      {
        actorId: actor.id,
        actorRole: actor.role,
        action: "payslip.recompute",
        targetType: "Payslip",
        targetId: id,
        before,
        after: row,
      },
      tx,
    );
    return row;
  });
}

export async function unvoidPayslip(
  id: string,
  actor: Actor,
): Promise<Payslip> {
  return db.transaction(async (tx) => {
    const [before] = await tx.select().from(payslips).where(eq(payslips.id, id));
    if (!before) throw new Error(`unvoidPayslip: ${id} not found`);
    if (!before.voidedAt) return before;
    const [row] = await tx
      .update(payslips)
      .set({ voidedAt: null, voidedById: null, voidReason: null })
      .where(eq(payslips.id, id))
      .returning();
    if (!row) throw new Error("unvoidPayslip: returning() empty");
    await recomputeRunTotal(tx, before.payrollRunId);
    await writeAudit(
      {
        actorId: actor.id,
        actorRole: actor.role,
        action: "payslip.unvoid",
        targetType: "Payslip",
        targetId: id,
        before,
        after: row,
      },
      tx,
    );
    return row;
  });
}

async function recomputeRunTotal(
  tx: Parameters<Parameters<typeof db.transaction>[0]>[0],
  runId: string,
): Promise<void> {
  const [agg] = await tx
    .select({
      total: sql<number>`COALESCE(SUM(${payslips.roundedPayCents}), 0)::int`,
    })
    .from(payslips)
    .where(and(eq(payslips.payrollRunId, runId), isNull(payslips.voidedAt)));
  const total = Number(agg?.total ?? 0);
  await tx
    .update(payrollRuns)
    .set({ totalAmountCents: total })
    .where(eq(payrollRuns.id, runId));
}
